{
    'name': 'Tadreb Live',
    'version': '1.0.0',
    'category': 'Education',
    'summary': 'Manage Groups',
    'description': """Groups""",
    'depends': ['mail', 'openeducat_core', 'openeducat_exam'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'views/menu.xml',
        'views/group_view.xml',
        'views/student_details_view.xml',
        'views/student_attendance_view.xml',
        'views/student_payment_view.xml',
        'report/report_student_details_template.xml',
        'report/report_student_attendance_details_template.xml',
        'report/report_student_payment_details_template.xml',
        'report/report.xml',
    ],
    'demo': [],
    'sequence': -150,
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
